import type { Metadata } from "next";
import { Navbar } from "@/app/components/Navbar";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body className="bg-[#f8f1e7] text-slate-900">

        <Navbar />   {/* ⬅️ NAVBAR BURADA OLMALI */}

        <main>{children}</main>

      </body>
    </html>
  );
}

